version: "3.4"

services:
  frontend-dev:
    container_name: frontend-dev
    user: ${CURRENT_UID}
    image: node:14.5.0-alpine3.12
    working_dir: /app/
    volumes:
      - .:/app/
    ports:
      - 3000:3000
      - 10000:10000
    command: sh -c "yarn install && yarn run dev"
    networks:
      default: